### ISSUE TITLE
MU safety analysis alerts about the same package version

### ISSUE THREAD

**Issue by ppetriuk** [f3flight/timmy-virgintest#8]
**Environment:**
Fuel Master MOS6.1MU4, not customised
OpenStack cloud deployed with MOS6.1 GA

**Steps:**
1. Execute  timmy-virgintest  with default settings
2.  In section MU safety analysis for fuel timmy-virgintest reports that:
fuel:
    - custom [builtin-md5] cobbler-web 2.4.4-1.mira1 may prevent MU0 version 2.4.4-1.mira1
    from being installed

**Comment by f3flight** [comment]
A recently introduced regression, will fix that.

**Comment by f3flight** [comment]
BTW, you say that cobbler-web 2.4.4-1.mira1 is not customized - I'll need to check that part too, it could be that this is another false positive (rpm md5 does not match the installed package files for some reason).

**Comment by f3flight** [comment]
```
[root@fuel timmy-virgintest]# dockerctl shell cobbler
[root@fuel /]# rpm --verify cobbler-web
.......T.    /usr/share/cobbler/web/cobbler.wsgi
S.5....T.    /usr/share/cobbler/web/settings.py
```

So it looks like another false positive. But why would you have cobbler-web installed on Fuel in the first place? It should be inside cobbler container only, and these are not checked (yet). I'm not sure this one should be added to exclusions yet.

**Comment by f3flight** [comment]
Polina, please pull the changes and check again  - should still show md5 issue for cobbler-web but should not show a message in MU safety check.

**Comment by f3flight** [comment]
@ppetriuk have you had a chance to re-try with a newer version?

**Comment by f3flight** [comment]
(please note the repo [has been renamed](https://github.com/f3flight/timmy-customtest/commit/910fcfa80ce82d7a78b746e4d28b272aee0c8d16) - by management's request :grinning: )

**Comment by ppetriuk** [comment]
Nope, sorry, can't get to it.

**Comment by f3flight** [comment]
Kkkklosed because of absence of updates! :stuck_out_tongue_closed_eyes:
