### ISSUE TITLE
Built-in md5 verification analysis: file access failure

### ISSUE THREAD

**Issue by ppetriuk** [f3flight/timmy-virgintest#9]
**Environment:**
Fuel Master MOS6.1MU4, not customised
OpenStack cloud deployed with MOS6.1 GA with Ubuntu

**Steps:**
1. Execute ./timmy-virgintest.py with default settings from fuel master:

   node 41 [controller]:
      perl 5.18.2-2ubuntu1:
        - 'usr/share/man/man1/pod2latex.1.gz: FAILED open or read'
        - 'usr/bin/pod2latex: FAILED'

**Comment by f3flight** [comment]
This is a known false positive, I've written about it in my email. I think I'll create a filtering file for md5 to filter such stuff.

**Comment by f3flight** [comment]
Should be now fixed with commit 091de3f799732339e917add329ade87ed5a84828 (this specific case only, if anything else pops up later let me know, I'll add to exclusions).
